### ISSUE TITLE
Move monitoring job into a CircleCI Orb

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-continuous#38]
The monitoring job / code introduced by https://github.com/adobe/helix-status/issues/46 is copied over across 15 repos! A change would require a lot of PRs. This code / job(s) could moved into a CircleCI Orb. A new release of the Orb would be detected by renovate and PRs would come automatically. 

cc @rofe

**Comment by trieloff** [comment]
- Post deployment test

**Comment by rofe** [comment]
Taking a step back after implementing #39, I wonder what we stand to gain if we replace the current monitoring setup command with a reference to an orb: when we change our monitoring setup, we will need to republish the orb and update all 15 repos to point to the new orb version. So we wouldn't actually decrease the number of PRs required...

**Comment by kptdobe** [comment]
Sure but renovate will generate the PRs for you...

**Comment by rofe** [comment]
Ah, right! 😅

**Comment by rofe** [comment]
> Post deployment test

On the other hand, many of the commands executed in `semantic-release` are actually defined in `package.json` (called using `npm run xyz`) - there's no real benefit in moving these to an orb, unless we plan to also remove them from package.json, which seems unpractical.

Focusing on commands which are defined directly in .circleci/config, I only see the following candidates for an orb:
- configure wsk
- configure env
- set up monitoring

**Comment by trieloff** [comment]
Updating one orb and then approving a couple of PRs definitely seems easier than (remembering to) update a couple of `package.json` files.

**Comment by rofe** [comment]
Ok. Let's see how this goes with the above 3 commands, and move more commands to the orb later on.

**Comment by rofe** [comment]
Implemented in https://github.com/adobe/helix-continuous/commit/4445a15b5b9045fa2db1795e296658f1ce475659. Will create PRs for helix service repos.
